### ISSUE TITLE
invoice error

### ISSUE THREAD

**Issue by jansorg** [jansorg/tom#4]
```
**
goroutine 1 [running]:
github.com/jansorg/gotime/gotime/frames.(*FrameList).FilterByEndDate.func1(0xc0000ee960, 0xc0000bdf00)
        /home/jansorg/go/src/github.com/jansorg/gotime/gotime/frames/frame_list.go:80 +0x38
github.com/jansorg/gotime/gotime/frames.(*FrameList).Filter(0xc0000bdf20, 0xc00014eb50)
        /home/jansorg/go/src/github.com/jansorg/gotime/gotime/frames/frame_list.go:101 +0xa2
github.com/jansorg/gotime/gotime/frames.(*FrameList).FilterByEndDate(0xc0000bdf20, 0x0, 0xed3bc9670, 0xd11fc0, 0x805300)
        /home/jansorg/go/src/github.com/jansorg/gotime/gotime/frames/frame_list.go:79 +0xca
github.com/jansorg/gotime/gotime/frames.(*FrameList).FilterByDatePtr(0xc0000bdf20, 0xc0000bdec0, 0xc0000bdee0, 0xd11f00)
        /home/jansorg/go/src/github.com/jansorg/gotime/gotime/frames/frame_list.go:94 +0xe9
github.com/jansorg/gotime/gotime/report.(*BucketReport).Update(0xc00014ee68)
        /home/jansorg/go/src/github.com/jansorg/gotime/gotime/report/report.go:58 +0x5e
github.com/jansorg/gotime/gotime/cmd.invoiceCmdConfig.createSummary(0xd12160, 0x0, 0xc0000b14a0, 0xc0000bdec0, 0xc0000bdee0, 0xc00015c240, 0x3d, 0x9cb560, 0xc0000f7680, 0x0, ...)
        /home/jansorg/go/src/github.com/jansorg/gotime/gotime/cmd/invoice.go:67 +0x1c6
github.com/jansorg/gotime/gotime/cmd.newSevdeskCommand.func1(0xc000152fc0, 0xc0000b0cc0, 0x0, 0x6)
        /home/jansorg/go/src/github.com/jansorg/gotime/gotime/cmd/invoice_sevdesk.go:27 +0x1af
github.com/spf13/cobra.(*Command).execute(0xc000152fc0, 0xc0000b0c00, 0x6, 0x6, 0xc000152fc0, 0xc0000b0c00)
        /home/jansorg/go/src/github.com/spf13/cobra/command.go:750 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0xd08da0, 0x0, 0x0, 0x0)
        /home/jansorg/go/src/github.com/spf13/cobra/command.go:831 +0x2dc
github.com/spf13/cobra.(*Command).Execute(0xd08da0, 0x4073c0, 0xc000094058)
        /home/jansorg/go/src/github.com/spf13/cobra/command.go:784 +0x2b
github.com/jansorg/gotime/gotime/cmd.Execute()
        /home/jansorg/go/src/github.com/jansorg/gotime/gotime/cmd/root.go:131 +0x2d
main.main()
        /home/jansorg/go/src/github.com/jansorg/gotime/gotime/main.go:11 +0x20
**
```

**Comment by jansorg** [comment]
invoice support has been removed
